Repository SWM-GSM/blabla-server, pull requests merged in 2023-08, with the labels that each got.

#109 feat: 크루 리포트 API 구현
  src/main/java/com/gsm/blabla/crew/api/CrewController.java
  src/main/java/com/gsm/blabla/crew/application/CrewService.java
  src/main/java/com/gsm/blabla/crew/dao/CrewReportAnalysisRepository.java
  src/main/java/com/gsm/blabla/crew/dao/VoiceFileRepository.java
  src/main/java/com/gsm/blabla/crew/domain/CrewReportAnalysis.java
  src/main/java/com/gsm/blabla/crew/dto/CrewReportResponseDto.java
  src/main/java/com/gsm/blabla/dummy/api/DummyController.java
  src/main/java/com/gsm/blabla/global/application/S3UploaderService.java
  src/main/java/com/gsm/blabla/global/response/Code.java
Labels: ☁️ feature

#110 feat: 애플 회원가입 API 구현 및 프론트 요청에 따른 API 수정
  src/main/java/com/gsm/blabla/auth/api/AuthController.java
  src/main/java/com/gsm/blabla/auth/application/AuthService.java
  src/main/java/com/gsm/blabla/global/response/Code.java
  src/main/java/com/gsm/blabla/jwt/TokenProvider.java
  src/main/java/com/gsm/blabla/jwt/dao/AppleAccountRepository.java
  src/main/java/com/gsm/blabla/jwt/domain/AppleAccount.java
  src/main/java/com/gsm/blabla/jwt/dto/AppleAccountDto.java
  src/main/java/com/gsm/blabla/jwt/dto/ApplePublicKeyDto.java
  src/main/java/com/gsm/blabla/jwt/dto/AppleTokenDto.java
  src/main/java/com/gsm/blabla/jwt/dto/JwtDto.java
  src/main/java/com/gsm/blabla/member/domain/SocialLoginType.java
Labels: ☁️ feature, 🧰 fix

#111 feat: 음성 채팅 유저 피드백 저장 API 구현
  src/main/java/com/gsm/blabla/crew/api/CrewController.java
  src/main/java/com/gsm/blabla/crew/application/CrewService.java
  src/main/java/com/gsm/blabla/crew/dao/FeedbackRepository.java
  src/main/java/com/gsm/blabla/crew/domain/Feedback.java
  src/main/java/com/gsm/blabla/crew/dto/VoiceFileFeedbackRequestDto.java
  src/main/java/com/gsm/blabla/dummy/api/DummyController.java
Labels: ☁️ feature, ♻️ refactor

#112 fix: 프론트 요청에 따른 API response 수정
  src/main/java/com/gsm/blabla/crew/api/CrewController.java
  src/main/java/com/gsm/blabla/crew/application/CrewService.java
  src/main/java/com/gsm/blabla/crew/application/ScheduleService.java
  src/main/java/com/gsm/blabla/crew/dao/MemberScheduleRepository.java
  src/main/java/com/gsm/blabla/crew/dto/ScheduleResponseDto.java
Labels: 🧰 fix

#113 test: jacoco 적용 및 테스트 코드 작성
  .gitignore
  build.gradle
  src/main/java/com/gsm/blabla/BlablaApplication.java
  src/main/java/com/gsm/blabla/crew/dto/CrewRequestDto.java
  src/main/java/com/gsm/blabla/crew/dto/MessageRequestDto.java
  src/main/java/com/gsm/blabla/global/config/JpaAuditingConfig.java
  src/test/java/com/gsm/blabla/crew/api/CrewControllerTest.java
  src/test/java/com/gsm/blabla/crew/application/CrewServiceTest.java
  src/test/java/com/gsm/blabla/crew/application/ScheduleServiceTest.java
  src/test/java/com/gsm/blabla/global/ControllerTestSupport.java
  src/test/java/com/gsm/blabla/global/DatabaseCleanup.java
  src/test/java/com/gsm/blabla/global/IntegrationTestSupport.java
  src/test/java/com/gsm/blabla/global/WithCustomMockUser.java
  src/test/java/com/gsm/blabla/global/WithCustomMockUserSecurityContextFactory.java
Labels: 🚀 test

#116 feat: 일정 참여 취소 API 구현
  src/main/java/com/gsm/blabla/crew/api/ScheduleController.java
  src/main/java/com/gsm/blabla/crew/application/ScheduleService.java
  src/main/java/com/gsm/blabla/crew/domain/MemberSchedule.java
  src/main/java/com/gsm/blabla/crew/domain/Schedule.java
  src/main/java/com/gsm/blabla/crew/dto/ScheduleResponseDto.java
  src/test/java/com/gsm/blabla/crew/application/ScheduleServiceTest.java
Labels: ☁️ feature

#118 fix: 각종 API 예외 처리
  src/main/java/com/gsm/blabla/auth/application/AuthService.java
  src/main/java/com/gsm/blabla/crew/api/CrewController.java
  src/main/java/com/gsm/blabla/crew/application/CrewService.java
  src/main/java/com/gsm/blabla/global/response/Code.java
  src/test/java/com/gsm/blabla/crew/application/CrewServiceTest.java
Labels: 🧰 fix

#121 feat: 컨텐츠 리스트 조회 API 수정
  src/main/java/com/gsm/blabla/dummy/api/DummyController.java
  src/main/java/com/gsm/blabla/practice/api/PracticeController.java
  src/main/java/com/gsm/blabla/practice/application/PracticeService.java
  src/main/java/com/gsm/blabla/practice/dao/ContentRepository.java
  src/main/java/com/gsm/blabla/practice/domain/Content.java
  src/main/java/com/gsm/blabla/practice/dto/ContentListResponseDto.java
  src/main/java/com/gsm/blabla/practice/dto/ContentResponseDto.java
  src/main/java/com/gsm/blabla/practice/dto/ContentViewResponseDto.java
Labels: ☁️ feature

#122 feat: 컨텐츠 조회 API 수정
  src/main/java/com/gsm/blabla/dummy/api/DummyController.java
  src/main/java/com/gsm/blabla/practice/dto/ContentResponseDto.java
Labels: ☁️ feature

#123 feat: 오늘의 컨텐츠 조회 더미 API 수정
  src/main/java/com/gsm/blabla/dummy/api/DummyController.java
Labels: ☁️ feature

#124 fix: token 오류 테스트를 위한 만료 기간 임시 변경
  src/main/java/com/gsm/blabla/jwt/TokenProvider.java
Labels: 🧰 fix

#125 fix: 토큰 만료 시간 원상 복구
  src/main/java/com/gsm/blabla/jwt/TokenProvider.java
Labels: 🧰 fix

#127 feat: 애플 로그인 API 구현
  src/main/java/com/gsm/blabla/auth/application/AuthService.java
Labels: ☁️ feature

#128 feat: 크루 리포트 단일 조회 및 목록 조회 API 구현
  src/main/java/com/gsm/blabla/crew/api/CrewController.java
  src/main/java/com/gsm/blabla/crew/application/CrewService.java
  src/main/java/com/gsm/blabla/crew/dao/CrewReportAnalysisRepository.java
  src/main/java/com/gsm/blabla/crew/dao/CrewReportRepository.java
  src/main/java/com/gsm/blabla/crew/dao/FeedbackRepository.java
  src/main/java/com/gsm/blabla/crew/domain/CrewReport.java
  src/main/java/com/gsm/blabla/crew/domain/Feedback.java
  src/main/java/com/gsm/blabla/crew/domain/VoiceFile.java
  src/main/java/com/gsm/blabla/crew/dto/CrewReportAnalysisResponseDto.java
  src/main/java/com/gsm/blabla/crew/dto/CrewReportResponseDto.java
  src/main/java/com/gsm/blabla/member/dto/MemberResponseDto.java
  src/test/java/com/gsm/blabla/crew/api/CrewControllerTest.java
  src/test/java/com/gsm/blabla/crew/application/CrewServiceTest.java
Labels: ☁️ feature

#130 feat: 크루 리포트 생성 API 키워드 저장 로직 추가
  src/main/java/com/gsm/blabla/crew/application/CrewService.java
  src/main/java/com/gsm/blabla/crew/dao/CrewReportKeywordRepository.java
  src/main/java/com/gsm/blabla/crew/domain/CrewReportKeyword.java
  src/main/java/com/gsm/blabla/crew/dto/AiCrewReportResponseDto.java
  src/main/java/com/gsm/blabla/crew/dto/CrewReportKeywordDto.java
  src/main/java/com/gsm/blabla/crew/dto/CrewReportResponseDto.java
Labels: ☁️ feature

#131 feat: 히스토리 조회 API 구현
  src/main/java/com/gsm/blabla/crew/api/CrewController.java
  src/main/java/com/gsm/blabla/crew/application/CrewService.java
  src/main/java/com/gsm/blabla/crew/dao/CrewReportRepository.java
  src/main/java/com/gsm/blabla/crew/dao/VoiceFileRepository.java
  src/main/java/com/gsm/blabla/dummy/api/DummyController.java
  src/main/java/com/gsm/blabla/practice/dao/MemberContentRepository.java
  src/main/java/com/gsm/blabla/report/api/ReportController.java
  src/main/java/com/gsm/blabla/report/application/ReportService.java
  src/main/java/com/gsm/blabla/report/dto/HistoryReportResponseDto.java
  src/main/java/com/gsm/blabla/report/dto/HistoryResponseDto.java
  src/test/java/com/gsm/blabla/crew/api/CrewControllerTest.java
  src/test/java/com/gsm/blabla/crew/application/CrewServiceTest.java
  src/test/java/com/gsm/blabla/global/ControllerTestSupport.java
  src/test/java/com/gsm/blabla/global/IntegrationTestSupport.java
  src/test/java/com/gsm/blabla/report/api/ReportControllerTest.java
  src/test/java/com/gsm/blabla/report/application/ReportServiceTest.java
Labels: ☁️ feature

#132 fix: 크루 리포트 단일 조회 API에 키워드 추가 및 테스트 코드 작성
  src/main/java/com/gsm/blabla/crew/application/CrewService.java
  src/main/java/com/gsm/blabla/crew/domain/CrewReport.java
  src/test/java/com/gsm/blabla/crew/application/CrewServiceTest.java
  src/test/java/com/gsm/blabla/global/IntegrationTestSupport.java
Labels: 🧰 fix

#137 fix: 회원 탈퇴 시 appleAccount, googleAccount, jwt 엔티티 삭제 로직 추가
  src/main/java/com/gsm/blabla/auth/application/AuthService.java
  src/main/java/com/gsm/blabla/jwt/dao/AppleAccountRepository.java
  src/main/java/com/gsm/blabla/jwt/dao/GoogleAccountRepository.java
  src/main/java/com/gsm/blabla/jwt/dao/JwtRepository.java
  src/main/java/com/gsm/blabla/member/application/MemberService.java
Labels: 🧰 fix

#138 fix: 연습실 피드백 생성 & 조회 dummy api에 answer 추가
  src/main/java/com/gsm/blabla/dummy/api/DummyController.java
Labels: 🧰 fix

#142 fix: 크루 일정 전체 조회 API members 타입 수정
  src/main/java/com/gsm/blabla/crew/dto/ScheduleResponseDto.java
Labels: 🧰 fix

#143 fix: 일정 전체 조회 API에서 참여 인원이 없을 경우 status를 NOT_JOINED로 수정
  src/main/java/com/gsm/blabla/crew/domain/MemberSchedule.java
  src/main/java/com/gsm/blabla/crew/dto/ScheduleResponseDto.java
Labels: 🧰 fix

#145 feat: 인공지능 엔드 포인트 수정
  src/main/java/com/gsm/blabla/crew/application/CrewService.java
  src/main/java/com/gsm/blabla/practice/application/PracticeService.java
Labels: ☁️ feature

#146 fix: 컨텐츠 조회 isCompleted 수정
  src/main/java/com/gsm/blabla/practice/dto/ContentViewResponseDto.java
Labels: 🧰 fix

#149 Revert "fix: 컨텐츠 조회 isCompleted 수정"
  src/main/java/com/gsm/blabla/practice/dto/ContentViewResponseDto.java
Labels: 🧰 fix

#153 feat: 크루 리포트 생성 요청 API 구현
  src/main/java/com/gsm/blabla/crew/api/CrewController.java
  src/main/java/com/gsm/blabla/crew/application/CrewService.java
  src/main/java/com/gsm/blabla/crew/dao/VoiceFileRepository.java
  src/main/java/com/gsm/blabla/global/response/Code.java
Labels: ☁️ feature

#154 fix: 크루 리포트 요청 API 파라미터 수정
  src/main/java/com/gsm/blabla/crew/application/CrewService.java
Labels: 🧰 fix

#156 feat: 설정값 조회 API 구현
  src/main/java/com/gsm/blabla/member/api/MemberController.java
  src/main/java/com/gsm/blabla/member/application/MemberService.java
Labels: ☁️ feature

#158 feature: 나의 memberId 조회 API와 memberId로 프로필 리스트 조회 API 구현
  src/main/java/com/gsm/blabla/member/api/MemberController.java
  src/main/java/com/gsm/blabla/member/application/MemberService.java
  src/main/java/com/gsm/blabla/member/dto/MemberRequestDto.java
Labels: ☁️ feature

#159 fix: 보이스룸 입장 API에 reportId 추가
  src/main/java/com/gsm/blabla/agora/application/AgoraService.java
  src/main/java/com/gsm/blabla/agora/dto/RtcTokenDto.java
  src/main/java/com/gsm/blabla/crew/dao/CrewReportRepository.java
Labels: 🧰 fix

#160 fix: 크루 리포트 조회 API 피드백을 작성하지 않은 경우 피드백 리스트에서 제외
  src/main/java/com/gsm/blabla/crew/application/CrewService.java
  src/main/java/com/gsm/blabla/member/dto/MemberResponseDto.java
Labels: 🧰 fix

#162 fix: 크루 가입 신청 API 승인제일 경우 Bad Request 문제 해결
  src/main/java/com/gsm/blabla/crew/api/CrewController.java
  src/main/java/com/gsm/blabla/crew/dto/MessageRequestDto.java
Labels: 🧰 fix

#163 fix: agora token 유효 기간 변경
  src/main/java/com/gsm/blabla/agora/application/AgoraService.java
Labels: 🧰 fix

#164 fix: Swagger API 명세서 기본 정보 기입
  src/main/java/com/gsm/blabla/global/config/SwaggerConfig.java
Labels: 🧰 fix

#166 fix: 히스토리 조회 API NullPointerException 오류 해결
  src/main/java/com/gsm/blabla/report/application/ReportService.java
Labels: 🧰 fix

#167 fix: 크루 리포트 목록 조회 API info가 null일 경우 createdAt, durationTime을 빈 문자열로 반환
  src/main/java/com/gsm/blabla/crew/application/CrewService.java
Labels: ☁️ feature

#168 fix: 크루 리포트 엔티티 endAt 수정
  src/main/java/com/gsm/blabla/crew/application/CrewService.java
  src/main/java/com/gsm/blabla/crew/domain/CrewReport.java
  src/main/java/com/gsm/blabla/crew/domain/CrewReportAnalysis.java
  src/main/java/com/gsm/blabla/report/application/ReportService.java
Labels: 🧰 fix

#169 fix: info가 null일 경우 createdAt과 durationTime 반환 양식을 변경
  src/main/java/com/gsm/blabla/crew/application/CrewService.java
Labels: 🧰 fix

#170 fix: crewReport의 endAt을 가져올 때 null exception 문제 해결
  src/main/java/com/gsm/blabla/crew/application/CrewService.java
  src/main/java/com/gsm/blabla/crew/domain/CrewReport.java
  src/main/java/com/gsm/blabla/report/application/ReportService.java
Labels: 🧰 fix

#171 fix: 크루 리포트 정보 조회 시 durationTime 계산 로직 변경
  src/main/java/com/gsm/blabla/crew/application/CrewService.java
  src/main/java/com/gsm/blabla/report/application/ReportService.java
Labels: 🧰 fix

#172 fix: crewReport의 endAt default 시각 변경
  src/main/java/com/gsm/blabla/crew/application/CrewService.java
  src/main/java/com/gsm/blabla/crew/domain/CrewReport.java
  src/main/java/com/gsm/blabla/report/application/ReportService.java
Labels: 🧰 fix

#174 fix: generated가 false인 리포트를 먼저 출력하도록 로직 변경
  src/main/java/com/gsm/blabla/crew/application/CrewService.java
Labels: 🧰 fix

#176 fix: generated가 true일 경우 createdAt을 기준 정렬 순서를 역순으로 변경
  src/main/java/com/gsm/blabla/crew/application/CrewService.java
Labels: 🧰 fix

#177 fix: CrewReportResponseDto 잘못된 정렬 reverse 위치 수정
  src/main/java/com/gsm/blabla/crew/application/CrewService.java
Labels: 🧰 fix
