Repository SWM-GSM/blabla-server, pull requests merged in 2023-09, with the labels that each got.

#187 fix: 디스코드 웹훅 도입으로 인한 테스트 코드 에러 수정 및 테스트 코드 보완
  build.gradle
  src/main/java/com/gsm/blabla/crew/domain/CrewReport.java
  src/main/java/com/gsm/blabla/global/exception/ExceptionHandler.java
  src/main/java/com/gsm/blabla/global/webhook/service/WebhookService.java
  src/test/java/com/gsm/blabla/BlablaApplicationTests.java
  src/test/java/com/gsm/blabla/crew/application/ScheduleServiceTest.java
  src/test/java/com/gsm/blabla/global/ControllerTestSupport.java
  src/test/java/com/gsm/blabla/global/IntegrationTestSupport.java
Labels: 🧰 fix

#191 fix: 컨텐츠 API 업데이트 및 조회 기능 수정
  src/main/java/com/gsm/blabla/dummy/api/DummyController.java
  src/main/java/com/gsm/blabla/global/response/Code.java
  src/main/java/com/gsm/blabla/practice/api/PracticeController.java
  src/main/java/com/gsm/blabla/practice/application/PracticeService.java
  src/main/java/com/gsm/blabla/practice/dao/ContentCategoryRepository.java
  src/main/java/com/gsm/blabla/practice/dao/ContentRepository.java
  src/main/java/com/gsm/blabla/practice/domain/Content.java
  src/main/java/com/gsm/blabla/practice/domain/ContentCategory.java
  src/main/java/com/gsm/blabla/practice/dto/ContentCategoryResponseDto.java
  src/main/java/com/gsm/blabla/practice/dto/ContentListResponseDto.java
  src/main/java/com/gsm/blabla/practice/dto/ContentResponseDto.java
  src/main/java/com/gsm/blabla/practice/dto/ContentViewResponseDto.java
  src/main/java/com/gsm/blabla/practice/dto/PracticeFeedbackRequestDto.java
  src/main/java/com/gsm/blabla/practice/dto/PracticeFeedbackResponseDto.java
  src/main/java/com/gsm/blabla/practice/dto/UserAnswerRequestDto.java
  src/main/java/com/gsm/blabla/report/application/ReportService.java
Labels: ☁️ feature, ♻️ refactor, 🧰 fix

#193 docs: PR Template 수정
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 📄 docs

#196 docs: PR Template 오타 수정 및 체크리스트 추가
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 📄 docs

#198 refactor: Member 엔티티 수정
  src/main/java/com/gsm/blabla/auth/application/AuthService.java
  src/main/java/com/gsm/blabla/crew/application/CrewService.java
  src/main/java/com/gsm/blabla/jwt/TokenProvider.java
  src/main/java/com/gsm/blabla/jwt/dto/GoogleAccountDto.java
  src/main/java/com/gsm/blabla/member/application/MemberService.java
  src/main/java/com/gsm/blabla/member/dao/MemberKeywordRepository.java
  src/main/java/com/gsm/blabla/member/domain/Member.java
  src/main/java/com/gsm/blabla/member/domain/MemberKeyword.java
  src/main/java/com/gsm/blabla/member/dto/MemberProfileRequestDto.java
  src/main/java/com/gsm/blabla/member/dto/MemberProfileResponseDto.java
  src/main/java/com/gsm/blabla/member/dto/MemberRequestDto.java
  src/main/java/com/gsm/blabla/member/dto/MemberResponseDto.java
Labels: ♻️ refactor

#200 fix: 테스트 코드 실행 안되는 문제 해결
  src/test/java/com/gsm/blabla/crew/api/CrewControllerTest.java
  src/test/java/com/gsm/blabla/global/IntegrationTestSupport.java
  src/test/java/com/gsm/blabla/global/WithCustomMockUserSecurityContextFactory.java
Labels: 🧰 fix

#201 refactor: 회원가입 API 수정 및 테스트 코드 작성
  src/main/java/com/gsm/blabla/auth/api/AuthController.java
  src/main/java/com/gsm/blabla/auth/application/AppleService.java
  src/main/java/com/gsm/blabla/auth/application/AuthService.java
  src/main/java/com/gsm/blabla/auth/application/GoogleService.java
  src/main/java/com/gsm/blabla/auth/dao/AppleAccountRepository.java
  src/main/java/com/gsm/blabla/auth/dao/GoogleAccountRepository.java
  src/main/java/com/gsm/blabla/auth/domain/AppleAccount.java
  src/main/java/com/gsm/blabla/auth/domain/GoogleAccount.java
  src/main/java/com/gsm/blabla/auth/dto/AppleAccountDto.java
  src/main/java/com/gsm/blabla/auth/dto/ApplePublicKeyDto.java
  src/main/java/com/gsm/blabla/auth/dto/AppleTokenDto.java
  src/main/java/com/gsm/blabla/auth/dto/GoogleAccountDto.java
  src/main/java/com/gsm/blabla/crew/application/CrewService.java
  src/main/java/com/gsm/blabla/member/application/MemberService.java
  src/main/java/com/gsm/blabla/member/dao/MemberRepository.java
  src/main/java/com/gsm/blabla/member/domain/nickname/Adjective.java
  src/main/java/com/gsm/blabla/member/domain/nickname/Animal.java
  src/main/java/com/gsm/blabla/member/domain/nickname/Color.java
  src/main/java/com/gsm/blabla/member/dto/MemberRequestDto.java
  src/test/java/com/gsm/blabla/auth/api/AuthControllerTest.java
  src/test/java/com/gsm/blabla/auth/application/AuthServiceTest.java
  src/test/java/com/gsm/blabla/crew/api/CrewControllerTest.java
  src/test/java/com/gsm/blabla/global/ControllerTestSupport.java
  src/test/java/com/gsm/blabla/global/DatabaseCleanup.java
  src/test/java/com/gsm/blabla/global/IntegrationTestSupport.java
Labels: ♻️ refactor, 🚀 test

#202 refactor: 컨텐츠 조회 API 수정 및 테스트 코드 작성
  src/main/java/com/gsm/blabla/content/api/ContentController.java
  src/main/java/com/gsm/blabla/content/application/ContentService.java
  src/main/java/com/gsm/blabla/content/dao/ContentDetailRepository.java
  src/main/java/com/gsm/blabla/content/dao/ContentRepository.java
  src/main/java/com/gsm/blabla/content/dao/MemberContentDetailRepository.java
  src/main/java/com/gsm/blabla/content/dao/PracticeHistoryRepository.java
  src/main/java/com/gsm/blabla/content/domain/Content.java
  src/main/java/com/gsm/blabla/content/domain/ContentDetail.java
  src/main/java/com/gsm/blabla/content/domain/MemberContentDetail.java
  src/main/java/com/gsm/blabla/content/domain/PracticeHistory.java
  src/main/java/com/gsm/blabla/content/dto/ContentDetailDto.java
  src/main/java/com/gsm/blabla/content/dto/ContentDetailResponseDto.java
  src/main/java/com/gsm/blabla/content/dto/ContentDetailsResponseDto.java
  src/main/java/com/gsm/blabla/content/dto/ContentsResponseDto.java
  src/main/java/com/gsm/blabla/content/dto/PracticeFeedbackRequestDto.java
  src/main/java/com/gsm/blabla/content/dto/PracticeFeedbackResponseDto.java
  src/main/java/com/gsm/blabla/content/dto/UserAnswerRequestDto.java
  src/main/java/com/gsm/blabla/global/response/Code.java
  src/main/java/com/gsm/blabla/practice/api/PracticeController.java
  src/main/java/com/gsm/blabla/practice/application/PracticeService.java
  src/main/java/com/gsm/blabla/practice/dao/ContentCategoryRepository.java
  src/main/java/com/gsm/blabla/practice/dao/ContentRepository.java
  src/main/java/com/gsm/blabla/practice/dao/MemberContentRepository.java
  src/main/java/com/gsm/blabla/practice/dto/ContentCategoryResponseDto.java
  src/main/java/com/gsm/blabla/practice/dto/ContentListResponseDto.java
  src/main/java/com/gsm/blabla/practice/dto/ContentResponseDto.java
  src/main/java/com/gsm/blabla/practice/dto/ContentViewResponseDto.java
  src/main/java/com/gsm/blabla/report/application/ReportService.java
  src/test/java/com/gsm/blabla/content/api/ContentControllerTest.java
  src/test/java/com/gsm/blabla/content/dao/ContentDetailRepositoryTest.java
  src/test/java/com/gsm/blabla/content/dao/ContentRepositoryTest.java
  src/test/java/com/gsm/blabla/global/ControllerTestSupport.java
Labels: ☁️ feature, ♻️ refactor, 🚀 test

#203 fix: 연습 기록 저장 API 수정
  src/main/java/com/gsm/blabla/content/api/ContentController.java
  src/main/java/com/gsm/blabla/content/application/ContentService.java
Labels: 🧰 fix

#206 fix: createPracticeHistory 테스트 오류 수정
  src/main/java/com/gsm/blabla/content/api/ContentController.java
Labels: 🧰 fix

#207 refactor: 크루 일정 관련 API 수정
  src/main/java/com/gsm/blabla/content/api/ContentController.java
  src/main/java/com/gsm/blabla/content/domain/Content.java
  src/main/java/com/gsm/blabla/content/dto/ContentDetailResponseDto.java
  src/main/java/com/gsm/blabla/crew/api/ScheduleController.java
  src/main/java/com/gsm/blabla/crew/application/ScheduleService.java
  src/main/java/com/gsm/blabla/crew/dao/MemberScheduleRepository.java
  src/main/java/com/gsm/blabla/crew/dao/ScheduleRepository.java
  src/main/java/com/gsm/blabla/crew/domain/Schedule.java
  src/main/java/com/gsm/blabla/crew/dto/ScheduleRequestDto.java
  src/main/java/com/gsm/blabla/crew/dto/ScheduleResponseDto.java
  src/main/java/com/gsm/blabla/global/response/Code.java
  src/test/java/com/gsm/blabla/content/api/ContentControllerTest.java
  src/test/java/com/gsm/blabla/content/dao/ContentDetailRepositoryTest.java
  src/test/java/com/gsm/blabla/content/dao/ContentRepositoryTest.java
  src/test/java/com/gsm/blabla/crew/api/ScheduleControllerTest.java
  src/test/java/com/gsm/blabla/crew/application/ScheduleServiceTest.java
  src/test/java/com/gsm/blabla/crew/dao/ScheduleRepositoryTest.java
  src/test/java/com/gsm/blabla/global/ControllerTestSupport.java
Labels: ♻️ refactor, 🚀 test

#208 fix: 회원가입 로직 수정
  src/main/java/com/gsm/blabla/auth/application/AuthService.java
  src/main/java/com/gsm/blabla/member/domain/nickname/Adjective.java
  src/main/java/com/gsm/blabla/member/domain/nickname/Animal.java
  src/main/java/com/gsm/blabla/member/domain/nickname/Color.java
  src/main/java/com/gsm/blabla/member/dto/MemberProfileRequestDto.java
  src/test/java/com/gsm/blabla/auth/application/AuthServiceTest.java
Labels: 🧰 fix

#212 fix: 보이스룸 입장 API 수정
  src/main/java/com/gsm/blabla/agora/api/AgoraController.java
  src/main/java/com/gsm/blabla/agora/application/AgoraService.java
  src/main/java/com/gsm/blabla/crew/application/CrewService.java
  src/main/java/com/gsm/blabla/crew/dao/CrewReportRepository.java
  src/main/java/com/gsm/blabla/crew/domain/CrewReport.java
  src/main/java/com/gsm/blabla/report/application/ReportService.java
Labels: 🧰 fix

#213 fix: 보이스룸 입장 API response 변경
  src/main/java/com/gsm/blabla/agora/application/AgoraService.java
  src/main/java/com/gsm/blabla/agora/dto/RtcTokenDto.java
Labels: 🧰 fix

#215 test: 테스트 코드 빌드 에러 수정
  src/test/java/com/gsm/blabla/agora/api/AgoraControllerTest.java
  src/test/java/com/gsm/blabla/agora/application/AgoraServiceTest.java
  src/test/java/com/gsm/blabla/global/IntegrationTestSupport.java
Labels: 🧰 fix

#216 fix: 컨텐츠의 thumbnailUrl 생성 로직 변경
  src/main/java/com/gsm/blabla/content/dto/ContentDetailDto.java
Labels: 🧰 fix

#217 fix: FCM 푸시 알림 전송 API 수정
  build.gradle
  src/main/java/com/gsm/blabla/admin/api/AdminController.java
  src/main/java/com/gsm/blabla/admin/application/FcmService.java
  src/main/java/com/gsm/blabla/admin/dto/PushMessageRequestDto.java
  src/main/java/com/gsm/blabla/fcm/api/FcmController.java
  src/test/java/com/gsm/blabla/global/ControllerTestSupport.java
Labels: 🧰 fix

#218 fix: 세부 컨텐츠 전체 조회 API response 수정
  src/main/java/com/gsm/blabla/content/application/ContentService.java
  src/main/java/com/gsm/blabla/content/dto/ContentDetailDto.java
Labels: 🧰 fix

#219 fix: 회원가입 API에서 pushNotification 제거
  src/main/java/com/gsm/blabla/member/domain/Member.java
  src/main/java/com/gsm/blabla/member/dto/MemberRequestDto.java
  src/test/java/com/gsm/blabla/auth/api/AuthControllerTest.java
  src/test/java/com/gsm/blabla/auth/application/AuthServiceTest.java
  src/test/java/com/gsm/blabla/crew/api/CrewControllerTest.java
  src/test/java/com/gsm/blabla/global/IntegrationTestSupport.java
Labels: 🧰 fix

#220 refactor: 크루 리포트 조회 API 리팩토링
  src/main/java/com/gsm/blabla/admin/application/FcmService.java
  src/main/java/com/gsm/blabla/agora/api/AgoraController.java
  src/main/java/com/gsm/blabla/agora/application/AgoraService.java
  src/main/java/com/gsm/blabla/content/dto/ContentDetailDto.java
  src/main/java/com/gsm/blabla/crew/api/CrewController.java
  src/main/java/com/gsm/blabla/crew/application/CrewService.java
  src/main/java/com/gsm/blabla/crew/dao/CrewReportRepository.java
  src/test/java/com/gsm/blabla/agora/api/AgoraControllerTest.java
  src/test/java/com/gsm/blabla/crew/api/CrewControllerTest.java
  src/test/java/com/gsm/blabla/crew/application/CrewServiceTest.java
  src/test/java/com/gsm/blabla/global/IntegrationTestSupport.java
  src/test/java/com/gsm/blabla/report/application/ReportServiceTest.java
Labels: ♻️ refactor, 🚀 test

#221 fix: FCM 푸시 알림 전송 API 에러 수정
  src/main/java/com/gsm/blabla/admin/api/AdminController.java
  src/main/java/com/gsm/blabla/admin/application/FcmService.java
  src/main/java/com/gsm/blabla/admin/dto/FcmMessage.java
  src/main/java/com/gsm/blabla/admin/dto/FcmMessageRequestDto.java
Labels: 🧰 fix

#222 refactor: 히스토리 조회 API 수정 및 사용하지 않는 파일 제거
  .github/workflows/ci-cd.yml
  build.gradle
  src/main/java/com/gsm/blabla/admin/api/AdminController.java
  src/main/java/com/gsm/blabla/agora/application/AgoraService.java
  src/main/java/com/gsm/blabla/common/enums/Keyword.java
  src/main/java/com/gsm/blabla/common/enums/Level.java
  src/main/java/com/gsm/blabla/common/enums/PreferMember.java
  src/main/java/com/gsm/blabla/common/enums/Tag.java
  src/main/java/com/gsm/blabla/crew/application/CrewService.java
  src/main/java/com/gsm/blabla/crew/dao/ApplyMessageRepository.java
  src/main/java/com/gsm/blabla/crew/dao/CrewAccuseRepository.java
  src/main/java/com/gsm/blabla/crew/dao/CrewMemberRepository.java
  src/main/java/com/gsm/blabla/crew/dao/CrewRepository.java
  src/main/java/com/gsm/blabla/crew/dao/CrewTagRepository.java
  src/main/java/com/gsm/blabla/crew/domain/ApplyMessage.java
  src/main/java/com/gsm/blabla/crew/domain/ApplyMessageStatus.java
  src/main/java/com/gsm/blabla/crew/domain/Crew.java
  src/main/java/com/gsm/blabla/crew/domain/CrewAccuse.java
  src/main/java/com/gsm/blabla/crew/domain/CrewAccuseType.java
  src/main/java/com/gsm/blabla/crew/domain/CrewMember.java
  src/main/java/com/gsm/blabla/crew/domain/CrewMemberRole.java
  src/main/java/com/gsm/blabla/crew/domain/CrewMemberStatus.java
  src/main/java/com/gsm/blabla/crew/domain/CrewReport.java
  src/main/java/com/gsm/blabla/crew/domain/CrewTag.java
  src/main/java/com/gsm/blabla/crew/domain/MeetingCycle.java
  src/main/java/com/gsm/blabla/crew/domain/Schedule.java
  src/main/java/com/gsm/blabla/crew/domain/VoiceFile.java
  src/main/java/com/gsm/blabla/crew/dto/CrewRequestDto.java
  src/main/java/com/gsm/blabla/crew/dto/CrewResponseDto.java
  src/main/java/com/gsm/blabla/crew/dto/MessageRequestDto.java
  src/main/java/com/gsm/blabla/report/application/ReportService.java
  src/test/java/com/gsm/blabla/agora/application/AgoraServiceTest.java
  src/test/java/com/gsm/blabla/crew/application/CrewServiceTest.java
  src/test/java/com/gsm/blabla/crew/application/ScheduleServiceTest.java
  src/test/java/com/gsm/blabla/global/DatabaseCleanup.java
  src/test/java/com/gsm/blabla/global/IntegrationTestSupport.java
  src/test/java/com/gsm/blabla/report/application/ReportServiceTest.java
Labels: ✈️ deploy, ♻️ refactor, 🚀 test

#223 fix: 애플 로그인 에러 수정
  src/main/java/com/gsm/blabla/auth/dto/AppleTokenDto.java
Labels: 🧰 fix

#224 fix: 애플 로그인 API 에러 수정
  src/main/java/com/gsm/blabla/auth/application/AppleService.java
  src/main/java/com/gsm/blabla/auth/dto/AppleAccountDto.java
Labels: 🧰 fix

#226 feat: 전체 컨텐츠, 세부 컨텐츠 조회 API 순서 기능 추가 및 테스트 코드 작성
  src/main/java/com/gsm/blabla/content/application/ContentService.java
  src/main/java/com/gsm/blabla/content/dao/ContentDetailRepository.java
  src/main/java/com/gsm/blabla/content/dao/ContentRepository.java
  src/main/java/com/gsm/blabla/content/domain/Content.java
  src/main/java/com/gsm/blabla/content/domain/ContentDetail.java
  src/test/java/com/gsm/blabla/content/dao/ContentDetailRepositoryTest.java
  src/test/java/com/gsm/blabla/content/dao/ContentRepositoryTest.java
  src/test/java/com/gsm/blabla/crew/dao/ScheduleRepositoryTest.java
  src/test/java/com/gsm/blabla/global/RepositoryTestSupport.java
Labels: ☁️ feature

#227 fix: 누락된 DatabaseCleanup 관련 코드 추가
  src/test/java/com/gsm/blabla/content/dao/ContentRepositoryTest.java
  src/test/java/com/gsm/blabla/global/RepositoryTestSupport.java
Labels: 🧰 fix

#230 feat: 보이스룸 접속 유저 목록 조회 API 구현
  src/main/java/com/gsm/blabla/agora/api/AgoraController.java
  src/main/java/com/gsm/blabla/agora/application/AgoraService.java
  src/main/java/com/gsm/blabla/agora/dao/VoiceRoomRepository.java
  src/main/java/com/gsm/blabla/agora/domain/VoiceRoom.java
  src/main/java/com/gsm/blabla/crew/api/CrewController.java
  src/main/java/com/gsm/blabla/crew/application/CrewService.java
  src/main/java/com/gsm/blabla/global/config/SecurityConfig.java
  src/main/java/com/gsm/blabla/global/response/Code.java
  src/main/java/com/gsm/blabla/member/dto/MemberResponseDto.java
  src/test/java/com/gsm/blabla/agora/api/AgoraControllerTest.java
  src/test/java/com/gsm/blabla/agora/application/AgoraServiceTest.java
  src/test/java/com/gsm/blabla/content/dao/ContentDetailRepositoryTest.java
  src/test/java/com/gsm/blabla/content/dao/ContentRepositoryTest.java
  src/test/java/com/gsm/blabla/crew/api/ScheduleControllerTest.java
  src/test/java/com/gsm/blabla/crew/dao/ScheduleRepositoryTest.java
  src/test/java/com/gsm/blabla/global/IntegrationTestSupport.java
Labels: ☁️ feature

#231 fix: webSecurityCustomizer에서 H2 관련 코드 제거
  src/main/java/com/gsm/blabla/global/config/SecurityConfig.java
Labels: 🧰 fix

#232 fix: SecurityConfig permitAll 대상 수정
  src/main/java/com/gsm/blabla/global/config/SecurityConfig.java
Labels: 🧰 fix

#236 fix: 연습 기록 음성 파일 저장 API 파라미터 수정
  src/main/java/com/gsm/blabla/content/api/ContentController.java
Labels: 🧰 fix

#238 feat: 이전 보이스룸 접속 유저 목록 조회 API 구현
  src/main/java/com/gsm/blabla/agora/api/AgoraController.java
  src/main/java/com/gsm/blabla/agora/application/AgoraService.java
  src/main/java/com/gsm/blabla/crew/dao/VoiceFileRepository.java
Labels: ☁️ feature

#239 fix: 음성 파일 분석 관련 API 수정
  src/main/java/com/gsm/blabla/crew/api/CrewController.java
  src/main/java/com/gsm/blabla/crew/application/CrewService.java
  src/main/java/com/gsm/blabla/crew/dao/VoiceFileAnalysisRepository.java
  src/main/java/com/gsm/blabla/crew/domain/VoiceFile.java
  src/main/java/com/gsm/blabla/crew/domain/VoiceFileAnalysis.java
  src/main/java/com/gsm/blabla/crew/dto/VoiceAnalysisResponseDto.java
  src/main/java/com/gsm/blabla/crew/dto/VoiceFileFeedbackRequestDto.java
  src/test/java/com/gsm/blabla/global/IntegrationTestSupport.java
Labels: 🧰 fix

#242 fix: 보이스룸 재접속 시 예외 처리를 반환하는 에러 수정
  src/main/java/com/gsm/blabla/agora/application/AgoraService.java
Labels: 🧰 fix

#244 test: codecov를 통한 커버리지 측정 도입
  .github/workflows/ci-cd.yml
  build.gradle
Labels: ⚙️ setting, 🚀 test

#249 fix: 음성 파일 분석 API 비어있는 음성 파일 예외 처리
  src/main/java/com/gsm/blabla/crew/application/CrewService.java
Labels: 🧰 fix

#251 fix: 리포트 생성 요청 API FCM targetToken 수정
  src/main/java/com/gsm/blabla/crew/api/CrewController.java
  src/main/java/com/gsm/blabla/crew/application/CrewService.java
  src/main/java/com/gsm/blabla/crew/domain/VoiceFile.java
  src/main/java/com/gsm/blabla/crew/dto/TargetTokenDto.java
Labels: 🧰 fix

#252 refactor: Content 관련 API 리팩토링
  src/main/java/com/gsm/blabla/content/application/ContentService.java
  src/main/java/com/gsm/blabla/content/dao/ContentDetailRepository.java
  src/main/java/com/gsm/blabla/content/dto/ContentDetailResponseDto.java
  src/main/java/com/gsm/blabla/content/dto/ContentsResponseDto.java
  src/test/java/com/gsm/blabla/content/api/ContentControllerTest.java
  src/test/java/com/gsm/blabla/content/application/ContentServiceTest.java
  src/test/java/com/gsm/blabla/content/dao/ContentDetailRepositoryTest.java
  src/test/java/com/gsm/blabla/content/dao/ContentRepositoryTest.java
  src/test/java/com/gsm/blabla/content/dao/MemberContentDetailRepositoryTest.java
  src/test/java/com/gsm/blabla/global/ControllerTestSupport.java
  src/test/java/com/gsm/blabla/global/IntegrationTestSupport.java
  src/test/java/com/gsm/blabla/global/RepositoryTestSupport.java
Labels: ♻️ refactor, 🧰 fix, 🚀 test

#253 deploy: prod 배포 주석 해제
  scripts/deploy.sh
Labels: ✈️ deploy

#255 deploy: 배포 스크립트 주석 해제
  scripts/deploy.sh
Labels: ✈️ deploy
