Repository SWM-GSM/blabla-server, pull requests merged in 2023-07, with the labels that each got.

#5 fix: Swagger 접속 안 되는 문제 해결
  src/main/java/com/gsm/blabla/global/config/SecurityConfig.java
Labels: 🧰 fix

#7 fix: 프론트엔드 요청에 따른 API 수정
  src/main/java/com/gsm/blabla/auth/api/AuthController.java
  src/main/java/com/gsm/blabla/auth/application/AuthService.java
  src/main/java/com/gsm/blabla/global/common/GeneralException.java
  src/main/java/com/gsm/blabla/global/common/api/EnumController.java
  src/main/java/com/gsm/blabla/global/common/dto/DataResponseDto.java
  src/main/java/com/gsm/blabla/global/common/dto/ErrorResponseDto.java
  src/main/java/com/gsm/blabla/global/common/dto/KeywordDto.java
  src/main/java/com/gsm/blabla/global/common/dto/ResponseDto.java
  src/main/java/com/gsm/blabla/global/common/enums/Code.java
  src/main/java/com/gsm/blabla/global/common/enums/Interest.java
  src/main/java/com/gsm/blabla/global/common/enums/Keyword.java
  src/main/java/com/gsm/blabla/global/common/enums/api/EnumController.java
  src/main/java/com/gsm/blabla/global/config/ExceptionHandler.java
  src/main/java/com/gsm/blabla/global/config/SecurityConfig.java
  src/main/java/com/gsm/blabla/jwt/TokenProvider.java
  src/main/java/com/gsm/blabla/member/dao/MemberInterestRepository.java
  src/main/java/com/gsm/blabla/member/domain/Member.java
  src/main/java/com/gsm/blabla/member/domain/MemberKeyword.java
  src/main/java/com/gsm/blabla/member/dto/MemberRequestDto.java
Labels: 🧰 fix

#8 fix: interest에서 keyword로 명칭 변경
  src/main/java/com/gsm/blabla/member/domain/Member.java
Labels: 🧰 fix

#10 refactor: Controller와 Service 분리
  build.gradle
  src/main/java/com/gsm/blabla/auth/api/AuthController.java
  src/main/java/com/gsm/blabla/auth/application/AuthService.java
  src/main/java/com/gsm/blabla/global/common/enums/Code.java
  src/main/java/com/gsm/blabla/global/domain/BaseTimeEntity.java
  src/main/java/com/gsm/blabla/global/enums/Code.java
  src/main/java/com/gsm/blabla/global/enums/Keyword.java
  src/main/java/com/gsm/blabla/global/enums/Level.java
  src/main/java/com/gsm/blabla/global/enums/api/EnumController.java
  src/main/java/com/gsm/blabla/global/enums/dto/KeywordDto.java
  src/main/java/com/gsm/blabla/global/exception/ExceptionHandler.java
  src/main/java/com/gsm/blabla/global/exception/GeneralException.java
  src/main/java/com/gsm/blabla/global/response/DataResponseDto.java
  src/main/java/com/gsm/blabla/global/response/ErrorResponseDto.java
  src/main/java/com/gsm/blabla/global/response/ResponseDto.java
  src/main/java/com/gsm/blabla/jwt/TokenProvider.java
  src/main/java/com/gsm/blabla/jwt/domain/GoogleAccount.java
  src/main/java/com/gsm/blabla/jwt/domain/Jwt.java
  src/main/java/com/gsm/blabla/member/api/MemberController.java
  src/main/java/com/gsm/blabla/member/application/MemberService.java
  src/main/java/com/gsm/blabla/member/domain/Member.java
  src/main/java/com/gsm/blabla/member/domain/MemberKeyword.java
  src/main/java/com/gsm/blabla/member/dto/MemberRequestDto.java
Labels: ♻️ refactor

#16 fix: workflow 에러 수정
  .github/workflows/github-actions.yml
Labels: ✈️ deploy, 🧰 fix

#17 deploy: Gradle Caching 단계 에러 수정
  .github/workflows/github-actions.yml
Labels: ✈️ deploy, 🧰 fix

#18 deploy: gradlew 권한 부여 단계 에러 수정
  .github/workflows/github-actions.yml
Labels: ✈️ deploy, 🧰 fix

#19 deploy: gradlew 권한 부여 단계 삭제
  .github/workflows/github-actions.yml
Labels: ✈️ deploy, 🧰 fix

#20 deploy: shell 지정 옵션 삭제
  .github/workflows/github-actions.yml
Labels: ✈️ deploy, 🧰 fix

#22 deploy: indent error 수정 및 jdk 버전 17로 수정
  .github/workflows/github-actions.yml
Labels: ✈️ deploy, 🧰 fix

#23 deploy: gradle 버전 명시
  .github/workflows/github-actions.yml
Labels: ✈️ deploy, 🧰 fix

#24 deploy: gradle build 스크립트 수정
  .github/workflows/github-actions.yml
Labels: ✈️ deploy, 🧰 fix

#26 deploy: gradle build 스크립트 수정
  .github/workflows/github-actions.yml
Labels: ✈️ deploy, 🧰 fix

#27 deploy: gradlew 권한 부여 단계 추가
  .github/workflows/github-actions.yml
Labels: ☁️ feature, 🧰 fix

#28 deploy: gradle wrapper init 단계 추가
  .github/workflows/github-actions.yml
Labels: ✈️ deploy, 🧰 fix

#29 deploy: gradle build 스크립트 수정
  .github/workflows/github-actions.yml
Labels: ✈️ deploy, 🧰 fix

#30 deploy: gradle build 에러 수정
  .github/workflows/github-actions.yml
Labels: ✈️ deploy, 🧰 fix

#31 feat: agora 채널 입장 API 구현
  src/main/java/com/gsm/blabla/agora/AccessToken2.java
  src/main/java/com/gsm/blabla/agora/ByteBuf.java
  src/main/java/com/gsm/blabla/agora/Packable.java
  src/main/java/com/gsm/blabla/agora/PackableEx.java
  src/main/java/com/gsm/blabla/agora/RtcTokenBuilder2.java
  src/main/java/com/gsm/blabla/agora/Utils.java
  src/main/java/com/gsm/blabla/agora/api/AgoraController.java
  src/main/java/com/gsm/blabla/agora/application/AgoraService.java
Labels: ☁️ feature

#35 deploy: Github Actions 스크립트 파일 수정
  .github/workflows/ci-cd.yml
Labels: ✈️ deploy, 🧰 fix

#37 feat: 컨텐츠 단일 조회 API 구현
  src/main/java/com/gsm/blabla/content/api/ContentController.java
  src/main/java/com/gsm/blabla/content/application/ContentService.java
  src/main/java/com/gsm/blabla/content/dao/ContentRepository.java
  src/main/java/com/gsm/blabla/content/domain/Content.java
  src/main/java/com/gsm/blabla/content/dto/ContentResponseDto.java
  src/main/java/com/gsm/blabla/crew/dao/CrewRepository.java
  src/main/java/com/gsm/blabla/global/response/Code.java
Labels: ☁️ feature

#38 feat: root 경로를 swagger 명세서로 리다이렉트
  src/main/java/com/gsm/blabla/global/config/WebConfig.java
Labels: ✈️ deploy, 🧰 fix

#41 deploy: github actions 스크립트 파일 수정
  .github/workflows/ci-cd.yml
Labels: ✈️ deploy, 🧰 fix

#42 deploy: CI/CD 에러 해결을 위해 trigger 변경
  .github/workflows/ci-cd.yml
Labels: ✈️ deploy, 🧰 fix

#43 deploy: gradle build 코드 수정 및 압축 코드 수정
  .github/workflows/ci-cd.yml
Labels: ✈️ deploy, 🧰 fix

#45 deploy: github actions 스크립트 수정
  .github/workflows/ci-cd.yml
Labels: ✈️ deploy, 🧰 fix

#47 deploy: submodule 설정 위치 변경
  .github/workflows/ci-cd.yml
Labels: ✈️ deploy, 🧰 fix

#52 fix: deploy.sh 배포 스크립트 수정
  scripts/deploy.sh
Labels: 🧰 fix

#53 fix: deploy.sh 배포 스크립트 수정
  scripts/deploy.sh
Labels: 🧰 fix

#54 fix: deploy.sh 배포 스크립트 수정
  scripts/deploy.sh
Labels: 🧰 fix

#56 feat: 조회 관련 dummy API 구현
  src/main/java/com/gsm/blabla/dummy/api/DummyController.java
Labels: ☁️ feature

#57 feat: 생성, 수정, 삭제 관련 dummy API 구현
  src/main/java/com/gsm/blabla/dummy/api/DummyController.java
  src/main/java/com/gsm/blabla/dummy/dto/AccuseDto.java
  src/main/java/com/gsm/blabla/dummy/dto/CrewDto.java
  src/main/java/com/gsm/blabla/dummy/dto/JoinDto.java
  src/main/java/com/gsm/blabla/dummy/dto/KeywordDto.java
  src/main/java/com/gsm/blabla/dummy/dto/MemberDto.java
  src/main/java/com/gsm/blabla/dummy/dto/ProfileDto.java
  src/main/java/com/gsm/blabla/dummy/dto/ReportDto.java
  src/main/java/com/gsm/blabla/dummy/dto/ScheduleDto.java
  src/main/java/com/gsm/blabla/dummy/dto/StatusDto.java
  src/main/java/com/gsm/blabla/dummy/dto/VoiceRoomDto.java
Labels: ☁️ feature

#59 fix: API response 수정
  src/main/java/com/gsm/blabla/agora/api/AgoraController.java
  src/main/java/com/gsm/blabla/agora/application/AgoraService.java
  src/main/java/com/gsm/blabla/agora/dto/RtcTokenDto.java
  src/main/java/com/gsm/blabla/crew/api/CrewController.java
  src/main/java/com/gsm/blabla/crew/api/ScheduleController.java
  src/main/java/com/gsm/blabla/crew/application/CrewService.java
  src/main/java/com/gsm/blabla/crew/application/ScheduleService.java
  src/main/java/com/gsm/blabla/crew/domain/Crew.java
  src/main/java/com/gsm/blabla/crew/dto/CrewRequestDto.java
  src/main/java/com/gsm/blabla/crew/dto/CrewResponseDto.java
  src/main/java/com/gsm/blabla/crew/dto/ScheduleResponseDto.java
  src/main/java/com/gsm/blabla/dummy/api/DummyController.java
  src/main/java/com/gsm/blabla/member/domain/Member.java
  src/main/java/com/gsm/blabla/member/dto/MemberRequestDto.java
  src/main/java/com/gsm/blabla/member/dto/MemberResponseDto.java
Labels: 🧰 fix

#60 feat: 크루 일정 전체 조회 API 구현
  src/main/java/com/gsm/blabla/crew/api/ScheduleController.java
  src/main/java/com/gsm/blabla/crew/application/ScheduleService.java
  src/main/java/com/gsm/blabla/crew/dao/ScheduleRepository.java
Labels: ☁️ feature

#62 feat: 크루 일정 참여하기 API 구현
  src/main/java/com/gsm/blabla/crew/api/ScheduleController.java
  src/main/java/com/gsm/blabla/crew/application/ScheduleService.java
  src/main/java/com/gsm/blabla/crew/dao/ScheduleRepository.java
  src/main/java/com/gsm/blabla/crew/dto/ScheduleRequestDto.java
  src/main/java/com/gsm/blabla/global/response/Code.java
Labels: ☁️ feature

#64 feat: 크루 가입 신청 API 구현
  src/main/java/com/gsm/blabla/crew/api/CrewController.java
  src/main/java/com/gsm/blabla/crew/application/CrewService.java
  src/main/java/com/gsm/blabla/crew/dao/ApplyMessageRepository.java
  src/main/java/com/gsm/blabla/crew/dao/CrewMemberRepository.java
  src/main/java/com/gsm/blabla/crew/domain/ApplyMessage.java
  src/main/java/com/gsm/blabla/crew/domain/CrewMember.java
  src/main/java/com/gsm/blabla/crew/dto/MessageRequestDto.java
  src/main/java/com/gsm/blabla/global/response/Code.java
  src/main/java/com/gsm/blabla/member/dto/MemberResponseDto.java
Labels: ☁️ feature

#65 hotfix: 크루 단일 조회 API 더미 데이터 수정
  src/main/java/com/gsm/blabla/dummy/api/DummyController.java
  src/main/java/com/gsm/blabla/dummy/dto/CrewDto.java
Labels: 🧰 fix

#66 feat: 크루 가입 승인 대기 인원 조회 API 구현
  src/main/java/com/gsm/blabla/crew/api/CrewController.java
  src/main/java/com/gsm/blabla/crew/application/CrewService.java
  src/main/java/com/gsm/blabla/crew/dao/ApplyMessageRepository.java
  src/main/java/com/gsm/blabla/crew/domain/ApplyMessage.java
  src/main/java/com/gsm/blabla/crew/domain/ApplyMessageStatus.java
  src/main/java/com/gsm/blabla/crew/domain/CrewMember.java
  src/main/java/com/gsm/blabla/crew/domain/CrewMemberStatus.java
  src/main/java/com/gsm/blabla/crew/dto/CrewResponseDto.java
  src/main/java/com/gsm/blabla/crew/dto/ScheduleResponseDto.java
  src/main/java/com/gsm/blabla/global/response/Code.java
  src/main/java/com/gsm/blabla/member/dto/MemberResponseDto.java
Labels: ☁️ feature

#67 fix: 크루 단일 조회 API에 status 추가
  src/main/java/com/gsm/blabla/crew/application/CrewService.java
  src/main/java/com/gsm/blabla/crew/dto/CrewResponseDto.java
Labels: 🧰 fix

#68 feat: 크루 가입 승인 및 거절 API 구현
  src/main/java/com/gsm/blabla/crew/api/CrewController.java
  src/main/java/com/gsm/blabla/crew/application/CrewService.java
  src/main/java/com/gsm/blabla/crew/domain/ApplyMessage.java
  src/main/java/com/gsm/blabla/crew/domain/CrewMember.java
  src/main/java/com/gsm/blabla/crew/dto/StatusRequestDto.java
  src/main/java/com/gsm/blabla/global/response/Code.java
Labels: ☁️ feature

#70 feat: 크루 신고하기 API 구현
  src/main/java/com/gsm/blabla/crew/api/CrewController.java
  src/main/java/com/gsm/blabla/crew/application/CrewService.java
  src/main/java/com/gsm/blabla/crew/dao/CrewAccuseRepository.java
  src/main/java/com/gsm/blabla/crew/domain/CrewAccuse.java
  src/main/java/com/gsm/blabla/crew/domain/CrewAccuseType.java
  src/main/java/com/gsm/blabla/crew/dto/AccuseRequestDto.java
Labels: ☁️ feature

#72 fix: 나의 크루 조회하기 API coverImage 수정
  src/main/java/com/gsm/blabla/dummy/api/DummyController.java
Labels: 🧰 fix

#75 feat: 크루 탈퇴 API 구현
  src/main/java/com/gsm/blabla/crew/api/CrewController.java
  src/main/java/com/gsm/blabla/crew/application/CrewService.java
  src/main/java/com/gsm/blabla/crew/application/ScheduleService.java
  src/main/java/com/gsm/blabla/crew/dao/CrewMemberRepository.java
  src/main/java/com/gsm/blabla/crew/domain/CrewMember.java
  src/main/java/com/gsm/blabla/crew/dto/ScheduleResponseDto.java
Labels: ☁️ feature

#76 feat: 크루 강제 탈퇴 API 구현
  src/main/java/com/gsm/blabla/crew/api/CrewController.java
  src/main/java/com/gsm/blabla/crew/application/CrewService.java
Labels: ☁️ feature

#79 fix: 컨텐츠 API 수정
  src/main/java/com/gsm/blabla/content/application/ContentService.java
  src/main/java/com/gsm/blabla/content/dao/MemberContentRepository.java
  src/main/java/com/gsm/blabla/content/domain/MemberContent.java
  src/main/java/com/gsm/blabla/content/dto/ContentListResponseDto.java
  src/main/java/com/gsm/blabla/content/dto/ContentViewResponseDto.java
Labels: 🧰 fix

#82 fix: content response 수정
  src/main/java/com/gsm/blabla/content/api/ContentController.java
  src/main/java/com/gsm/blabla/content/application/ContentService.java
  src/main/java/com/gsm/blabla/content/dto/ContentListResponseDto.java
  src/main/java/com/gsm/blabla/content/dto/ContentResponseDto.java
  src/main/java/com/gsm/blabla/content/dto/ContentViewResponseDto.java
Labels: 🧰 fix

#88 feat: 유저 프로필 조회 API 구현
  src/main/java/com/gsm/blabla/crew/api/CrewController.java
  src/main/java/com/gsm/blabla/crew/application/CrewService.java
  src/main/java/com/gsm/blabla/member/api/MemberController.java
  src/main/java/com/gsm/blabla/member/application/MemberService.java
  src/main/java/com/gsm/blabla/member/dao/MemberKeywordRepository.java
  src/main/java/com/gsm/blabla/member/domain/MemberKeyword.java
  src/main/java/com/gsm/blabla/member/dto/MemberResponseDto.java
Labels: ☁️ feature

#90 chore: .gitignore에 prod 설정파일 추가
  .gitignore
Labels: ✈️ deploy

#89 feat: profile update API 구현
  src/main/java/com/gsm/blabla/member/api/MemberController.java
  src/main/java/com/gsm/blabla/member/application/MemberService.java
  src/main/java/com/gsm/blabla/member/dao/MemberKeywordRepository.java
  src/main/java/com/gsm/blabla/member/domain/Member.java
  src/main/java/com/gsm/blabla/member/dto/MemberRequestDto.java
Labels: ☁️ feature

#91 feat: 멤버 삭제 API 구현
  src/main/java/com/gsm/blabla/member/api/MemberController.java
  src/main/java/com/gsm/blabla/member/application/MemberService.java
  src/main/java/com/gsm/blabla/member/domain/Member.java
Labels: ☁️ feature

#92 feat: 프로필 조회 API 구현
  src/main/java/com/gsm/blabla/crew/application/CrewService.java
  src/main/java/com/gsm/blabla/member/api/MemberController.java
  src/main/java/com/gsm/blabla/member/application/MemberService.java
  src/main/java/com/gsm/blabla/member/dto/MemberResponseDto.java
Labels: ☁️ feature

#93 fix: MemberRequestDto Wrapper class로 변경
  src/main/java/com/gsm/blabla/member/domain/Member.java
  src/main/java/com/gsm/blabla/member/dto/MemberRequestDto.java
Labels: 🧰 fix

#95 fix: profile dummy api
  src/main/java/com/gsm/blabla/dummy/api/DummyController.java
Labels: 🧰 fix

#94 deploy: 배포 스크립트 변경
  scripts/deploy.sh
Labels: ✈️ deploy

#96 deploy: 환경별 nohup.out 분리
  scripts/deploy.sh
Labels: ✈️ deploy

#98 feat: 프로필 조회 keywords tag 추가
  src/main/java/com/gsm/blabla/crew/application/CrewService.java
  src/main/java/com/gsm/blabla/dummy/api/DummyController.java
  src/main/java/com/gsm/blabla/member/application/MemberService.java
  src/main/java/com/gsm/blabla/member/dto/MemberResponseDto.java
Labels: ☁️ feature

#99 feat: dummy profile API 생년월일 추가
  src/main/java/com/gsm/blabla/dummy/api/DummyController.java
Labels: ☁️ feature

#100 feat: 연습실 피드백 생성 API 구현 & 더미 데이터 추가
  src/main/java/com/gsm/blabla/content/api/ContentController.java
  src/main/java/com/gsm/blabla/content/application/ContentService.java
  src/main/java/com/gsm/blabla/dummy/api/DummyController.java
  src/main/java/com/gsm/blabla/practice/api/PracticeController.java
  src/main/java/com/gsm/blabla/practice/application/PracticeService.java
  src/main/java/com/gsm/blabla/practice/dao/ContentRepository.java
  src/main/java/com/gsm/blabla/practice/dao/MemberContentRepository.java
  src/main/java/com/gsm/blabla/practice/domain/Content.java
  src/main/java/com/gsm/blabla/practice/domain/MemberContent.java
  src/main/java/com/gsm/blabla/practice/dto/ContentListResponseDto.java
  src/main/java/com/gsm/blabla/practice/dto/ContentResponseDto.java
  src/main/java/com/gsm/blabla/practice/dto/ContentViewResponseDto.java
  src/main/java/com/gsm/blabla/practice/dto/PracticeFeedbackRequestDto.java
  src/main/java/com/gsm/blabla/practice/dto/PracticeFeedbackResponseDto.java
Labels: ☁️ feature

#101 feat: 연습실 피드백 조회 API 구현 & 더미 데이터 추가
  src/main/java/com/gsm/blabla/dummy/api/DummyController.java
  src/main/java/com/gsm/blabla/global/response/Code.java
  src/main/java/com/gsm/blabla/practice/api/PracticeController.java
  src/main/java/com/gsm/blabla/practice/application/PracticeService.java
Labels: ☁️ feature

#102 feat: 프로필 생년월일, 성별, 푸쉬 알림 여부 수정 API 구현 & 더미 데이터 추가
  src/main/java/com/gsm/blabla/dummy/api/DummyController.java
  src/main/java/com/gsm/blabla/member/api/MemberController.java
  src/main/java/com/gsm/blabla/member/application/MemberService.java
  src/main/java/com/gsm/blabla/member/domain/Member.java
  src/main/java/com/gsm/blabla/member/dto/BirthDateDisclosureRequestDto.java
  src/main/java/com/gsm/blabla/member/dto/PushNotificationRequestDto.java
  src/main/java/com/gsm/blabla/member/dto/genderDisclosureRequestDto.java
Labels: ☁️ feature

#103 fix: 연습실 피드백 생성 API RequestParam to RequestBody 수정
  src/main/java/com/gsm/blabla/dummy/api/DummyController.java
  src/main/java/com/gsm/blabla/practice/api/PracticeController.java
  src/main/java/com/gsm/blabla/practice/application/PracticeService.java
  src/main/java/com/gsm/blabla/practice/dto/UserAnswerRequestDto.java
Labels: 🧰 fix

#104 feat: 크루 멤버 프로필 조회 API 공개 여부에 따른 조회 기능 추가
  src/main/java/com/gsm/blabla/crew/api/CrewController.java
  src/main/java/com/gsm/blabla/crew/application/CrewService.java
  src/main/java/com/gsm/blabla/member/api/MemberController.java
  src/main/java/com/gsm/blabla/member/application/MemberService.java
  src/main/java/com/gsm/blabla/member/dto/MemberProfileResponseDto.java
  src/main/java/com/gsm/blabla/member/dto/MemberResponseDto.java
Labels: ☁️ feature

#105 fix: 프로필 조회 더미 데이터 수정
  src/main/java/com/gsm/blabla/dummy/api/DummyController.java
Labels: 🧰 fix

#106 feat: 프로필 수정 API 역할 분리 & 더미 데이터 추가
  src/main/java/com/gsm/blabla/dummy/api/DummyController.java
  src/main/java/com/gsm/blabla/member/api/MemberController.java
  src/main/java/com/gsm/blabla/member/application/MemberService.java
  src/main/java/com/gsm/blabla/member/domain/Member.java
  src/main/java/com/gsm/blabla/member/dto/DescriptionRequestDto.java
  src/main/java/com/gsm/blabla/member/dto/KeywordsRequestDto.java
  src/main/java/com/gsm/blabla/member/dto/MemberProfileRequestDto.java
  src/main/java/com/gsm/blabla/member/dto/MemberProfileResponseDto.java
Labels: ☁️ feature

#107 refactor: 음성 파일 업로드 분석 API 단일 파일 업로드로 변경
  src/main/java/com/gsm/blabla/crew/api/CrewController.java
  src/main/java/com/gsm/blabla/crew/application/CrewService.java
  src/main/java/com/gsm/blabla/global/application/S3UploaderService.java
Labels: ♻️ refactor

#108 feat: 연습 기록 음성 파일 저장 API 구현
  src/main/java/com/gsm/blabla/dummy/api/DummyController.java
  src/main/java/com/gsm/blabla/global/response/Code.java
  src/main/java/com/gsm/blabla/practice/api/PracticeController.java
  src/main/java/com/gsm/blabla/practice/application/PracticeService.java
  src/main/java/com/gsm/blabla/practice/dao/PracticeHistoryRepository.java
  src/main/java/com/gsm/blabla/practice/domain/PracticeHistory.java
Labels: ☁️ feature
